version: '3'

services:
  catalogdb:
    image: mongo
    networks:
      - mynetwork
  basketdb:
    image: redis
    networks:
      - mynetwork
  discount:
    image: postgres
    networks:
      - mynetwork
  identitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - mynetwork
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - mynetwork
  rabbitmq:
    image: rabbitmq:4.0.5-management
    networks:
      - mynetwork
  catalog.api:
    image: catalog_api_image
    build:
      context: .
      dockerfile: Services/Catalog/FreeCourse.Services.Catalog/Dockerfile
    networks:
      - mynetwork
  basket.api:
    image: basket_api_image
    build:
      context: .
      dockerfile: Services/Basket/FreeCourse.Services.Basket/Dockerfile
    networks:
      - mynetwork
  photostock.api:
    image: photostock_api_image
    build:
      context: .
      dockerfile: Services/PhotoStock/FreeCourse.Services.PhotoStock/Dockerfile
    networks:
      - mynetwork
  discount.api:
    image: discount_api_image
    build:
      context: .
      dockerfile: Services/Discount/FreeCourse.Services.Discount/Dockerfile
    networks:
      - mynetwork
  fakepayment.api:
    image: fakepayment_api_image
    build:
      context: .
      dockerfile: Services/FakePayment/FreeCourse.Services.FakePayment/Dockerfile
    networks:
      - mynetwork
  order.api:
    image: order_api_image
    build:
      context: .
      dockerfile: Services/Order/FreeCourse.Services.Order.API/Dockerfile
    networks:
      - mynetwork
  gateway.api:
    image: gateway_api_image
    build:
      context: .
      dockerfile: FreeCourse.Gateway/Dockerfile
    networks:
      - mynetwork
  aspnetcoremvc.web:
    image: aspnetcoremvc.web_image
    build:
      context: .
      dockerfile: Frontends/FreeCourse.Web/Dockerfile
    networks:
      - mynetwork
  identityserver.api:
    image: identityserver_api_image
    build:
      context: .
      dockerfile: IdentityServer/FreeCourse.IdentityServer/Dockerfile
    networks:
      - mynetwork

volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:

networks:
  mynetwork:
    driver: bridge
